### ISSUE TITLE
the dropdown content is overflowing

### ISSUE THREAD

**Issue by ritz078** [ritz078/raaga#119]
<img width="259" alt="Screenshot 2021-01-31 at 4 56 23 PM" src="https://user-images.githubusercontent.com/5389035/106382388-4f0f5e80-63e5-11eb-9c58-c2457f79c362.png">

**Comment by agent515** [comment]
List is very long. So, I think you'd require a scroll bar for the container with the same height (300px). Am I right?

**Comment by agent515** [comment]
![image](https://user-images.githubusercontent.com/46898603/106384176-9e5a8c80-63ef-11eb-9018-0538d59a4ac0.png)
Interestingly, it works fine in the localhost.

**Comment by ritz078** [comment]
That's interesting. Are you using the same browser when testing localhost and production ?

**Comment by agent515** [comment]
Yes. I'm using Microsoft Edge.

**Comment by ritz078** [comment]
> I'm using Microsoft Edge.

Is it the new chromium edge or the old one ?

Can you tell me the version ?

**Comment by agent515** [comment]
Chromium edge

88.0.705.56

**Comment by ritz078** [comment]
Can you add  the style `max-height: 300px;` to  https://github.com/ritz078/raaga/blob/67193394cea64dafa80db68b88e545f92b4c9027/components/WriteModeControls/WriteModeControls.tsx#L58 and open a PR ? 

All the Prs are automatically deployed so we will be able to test if that fixes the dropdown in production.

**Comment by agent515** [comment]
Okay.
